# Generated by Django 3.2.15 on 2022-09-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, default='77f93e65e0a7410e92c21ee4f8ee1bd6', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
