# Generated by Django 3.2.15 on 2022-09-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0002_alter_budget_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, default='534c5195136044c994883c62baf74ecb', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
