# Generated by Django 3.2.15 on 2022-09-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0003_alter_budget_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, default='5e3a3def691541ffb70f9892c4f6070b', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
