# Generated by Django 3.2.15 on 2022-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0005_alter_budget_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetitems',
            options={'ordering': ['name'], 'verbose_name': 'Budget Item', 'verbose_name_plural': 'Budget Items'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, default='d526ba0b622649669147f46be079b103', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='budgetitems',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar'), ('€', 'Euro')], default='usd', max_length=20),
        ),
    ]
