# Generated by Django 3.2.15 on 2022-09-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0011_auto_20220925_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added ad'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, default='059027b6e97a419f83e44bc6bc7c643e', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
