# Generated by Django 3.2.15 on 2022-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_budget', '0012_auto_20220925_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, default='498343ab446848f596dd90cd3a443524', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
