# Generated by Django 3.2.15 on 2022-09-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220922_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, default='891e1264cb9c43b4a35402e06e797b90', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
