# Generated by Django 3.2.15 on 2022-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220923_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, default='1031df14738f40dfad8749397516acb6', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
