# Generated by Django 3.2.15 on 2022-09-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_family_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, default='040ba450ae6b444e9fcddeab31ec4842', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
