# Generated by Django 3.2.15 on 2022-09-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_family_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, default='ad9b5e9792874c9b9b34080bf8d4723c', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
