# Generated by Django 3.2.15 on 2022-09-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_family_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, default='4793a57e2d0c4af39f049cdcd98b1da5', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
