# Generated by Django 3.2.15 on 2022-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_family_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.SlugField(blank=True, default='f8780cbe2e404c4894a180a67d597d18', max_length=150, null=True, unique=True, verbose_name='Link'),
        ),
    ]
